### ISSUE TITLE
Profile page enhancement

### ISSUE THREAD

**Issue by Sarlianth** [Sarlianth/DataRepProject2016#1]
It would be a great idea to work on the profile page to make it look better and not as boring as it is now. I was thinking of adding avatars and some basic user information. It would also be great to allow users to edit their profiles. I was thinking of using the Gravatar service for generating avatars, so we wouldn't have to store the images on our server.

**Comment by adriangoliasgti** [comment]
Gravatar sounds great, did a bit of research on it too. Also found this useful link here which gives you an overview of what will we deal with if we decide to use it afterall. 

[https://en.gravatar.com/site/implement/](url)

Bellow is also a sample code I found which doesn't seem to be difficult to deal with honestly.

`# import code for encoding urls and generating md5 hashes
import urllib, hashlib

# Set your variables here
email = "someone@somewhere.com"
default = "https://www.example.com/default.jpg"
size = 40
 
# construct the url
gravatar_url = "https://www.gravatar.com/avatar/" + hashlib.md5(email.lower()).hexdigest() + "?"
gravatar_url += urllib.urlencode({'d':default, 's':str(size)})`

Since it doesn't seem complex and looks simple I think using Gravatar is the real deal here. Lets just use it, see how it works and perhaps see if it will suit our project. In case you would prefer something else, perhaps Avatars is a good option to use. Here is a link to their website [https://www.avatars.io/](url) and note that they also made it easy to make a transition from Gravatar to Avatars. So if we get the Gravatar API working with our project then transitioning to Avatars API shouldn't be any problem as they provide all the info on their website and it is matter of changing few lines of code only. Check it out for yourselves we'll talk about it during our next meeting.
