### ISSUE TITLE
Nickname Duplication

### ISSUE THREAD

**Issue by adriangoliasgti** [Sarlianth/DataRepProject2016#3]
Since there are two Adrians in the database it generates an error on Login because there can only be one unique nickname. Therefor we need to deal with this issue asap. Do you guys have any suggestions?

**Comment by RobertKiliszewski** [comment]
I have noticed that and I will try to do my best creating a new method to create random user nicknames. I still don't know how to handle the duplicate nicknames in the view function for the edit profile page. Since user is selecting the username himself we need to send that to the database to check if it exists and validate it. I will work on it now and hopefully will get it sorted asap.
